package com.agentic.orchestrator.agents;

import com.agentic.orchestrator.core.Decision;
import com.agentic.orchestrator.core.ExecutionContext;
import com.agentic.orchestrator.core.Gate;
import com.agentic.orchestrator.core.Stage;
import com.agentic.orchestrator.core.StageResult;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/** Regenerates url-shortener/README.md from whatever {@link ImplementationAgent} last produced. */
public final class DocumentationAgent implements Stage {

    private final String templateSet;

    public DocumentationAgent(String templateSet) {
        this.templateSet = templateSet;
    }

    @Override
    public String id() {
        return "documentation";
    }

    @Override
    public String description() {
        return "Regenerate API docs for template set '" + templateSet + "'";
    }

    @Override
    public List<String> dependsOn() {
        return List.of("implementation");
    }

    @Override
    public Gate entryGate() {
        return ctx -> Boolean.TRUE.equals(ctx.getArtifact("implementationChanged"))
                ? Gate.GateResult.pass("implementation completed")
                : Gate.GateResult.fail("no implementation artifact to document");
    }

    @Override
    public Gate exitGate() {
        return ctx -> Boolean.TRUE.equals(ctx.getArtifact("docsGenerated"))
                ? Gate.GateResult.pass("docs written")
                : Gate.GateResult.fail("docsGenerated artifact missing");
    }

    @Override
    public StageResult execute(ExecutionContext ctx) throws IOException {
        String architecture = ctx.getArtifact("architectureDecision");
        String body = renderMarkdown(templateSet, architecture == null ? "n/a" : architecture);

        Path docsPath = ctx.workspaceRoot().resolve("url-shortener").resolve("README.md");
        Files.writeString(docsPath, body);

        ctx.recordDecision(Decision.of(id(),
                "regenerated README.md for template set '" + templateSet + "'",
                "docs must stay 1:1 with whatever implementation delta actually shipped"));
        ctx.putArtifact("docsGenerated", true);
        ctx.putArtifact("docsPath", docsPath.toString());

        return StageResult.success("wrote " + docsPath.getFileName());
    }

    private String renderMarkdown(String set, String architecture) {
        StringBuilder md = new StringBuilder();
        md.append("# URL Shortener API\n\n");
        md.append("_Generated by the agentic orchestrator's DocumentationAgent for template set `")
                .append(set).append("`._\n\n");
        md.append("## Architecture\n\n").append(architecture).append("\n\n");
        md.append("## Endpoints\n\n");

        md.append("### `POST /api/shorten`\n\n");
        md.append("Request body:\n```json\n{\n  \"longUrl\": \"https://example.com/some/page\",\n");
        if (set.equals("brownfield")) {
            md.append("  \"customAlias\": \"my-alias\",\n");
        }
        md.append("  \"ttlSeconds\": 3600\n}\n```\n");
        if (set.equals("brownfield")) {
            md.append("`customAlias` and `ttlSeconds` are both optional. A taken alias returns `409 Conflict`.\n\n");
        } else {
            md.append("`ttlSeconds` is optional; omit it for a link that never expires.\n\n");
        }

        md.append("### `GET /{code}`\n\n302 redirect to the original URL, or `404` if unknown/expired.\n\n");

        md.append("### `GET /api/analytics/{code}`\n\nReturns click count");
        if (set.equals("ambiguous")) {
            md.append(", createdAt and lastAccessedAt.\n\n");
        } else {
            md.append(" and createdAt.\n\n");
        }

        md.append("### `GET /health`\n\nLiveness probe, always `200 {\"status\":\"UP\"}`.\n\n");

        md.append("## Reliability\n\n");
        md.append("- Input validation on `longUrl` (must be an absolute http(s) URL, max 2048 chars)\n");
        md.append("- Fixed-window rate limiting per client IP on the create endpoint\n");
        md.append("- Optional TTL-based expiration, enforced on every resolve\n");
        if (set.equals("brownfield") || set.equals("brownfield-bugfix-only")) {
            md.append("- Fixed: expired links no longer count toward click analytics\n");
        }
        md.append('\n');
        return md.toString();
    }
}
